//export const SETDATA = 'SETDATA';

export const SET_INPUTVALUE = 'SET_INPUTVALUE';

export const SETTABINDEX = 'SETTABINDEX';

export const SETSECTIONINDEX = 'SETSECTIONINDEX'

//export const SETCLOSEON = "SETCLOSEON"

export const SET_ROWINDEX = "SET_ROWINDEX"


//export const SET_NAVIGATIONPARAMS = "SET_NAVIGATIONPARAMS"

export const SET_MASKFLAG = "SET_MASKFLAG"

export const SET_SCROLLENABLED = "SET_SCROLLENABLED"

export const SET_NAVIGATIONDATA = "SET_NAVIGATIONDATA"

export const SET_MULTITREEDATA = 'SET_MULTITREEDATA'

export const SET_BOTTOMHEIGHT = 'SET_BOTTOMHEIGHT'

export const SET_TOPHEIGHT = "SET_TOPHEIGHT"

//export const SET_BUTTONINDEX = "SET_BUTTONINDEX"


