"use strict";
//export const SETDATA = 'SETDATA';
Object.defineProperty(exports, "__esModule", { value: true });
exports.SET_INPUTVALUE = 'SET_INPUTVALUE';
exports.SETTABINDEX = 'SETTABINDEX';
exports.SETSECTIONINDEX = 'SETSECTIONINDEX';
//export const SETCLOSEON = "SETCLOSEON"
exports.SET_ROWINDEX = "SET_ROWINDEX";
//export const SET_NAVIGATIONPARAMS = "SET_NAVIGATIONPARAMS"
exports.SET_MASKFLAG = "SET_MASKFLAG";
exports.SET_SCROLLENABLED = "SET_SCROLLENABLED";
exports.SET_NAVIGATIONDATA = "SET_NAVIGATIONDATA";
exports.SET_MULTITREEDATA = 'SET_MULTITREEDATA';
exports.SET_BOTTOMHEIGHT = 'SET_BOTTOMHEIGHT';
exports.SET_TOPHEIGHT = "SET_TOPHEIGHT";
//export const SET_BUTTONINDEX = "SET_BUTTONINDEX"
